config/routes.rb
Getautodeal::Application.routes.draw do

  resources :users, :except => [:edit]
  match '/index', :to => 'pages#index'
  match '/page2', :to => 'pages#page2' 
  match '/page3', :to => 'pages#page3' 
  match '/contact_us', :to => 'pages#contact_us'
  match '/help', :to => 'pages#help'
  match '/faq', :to => 'pages#faq'

  root :to => "pages#index"

end

app/models/car.rb
class Car < ActiveRecord::Base

  attr_accessible :make, :model, :description
  
  validates :make, :presence => true
  validates :model, :presence => true
  validates :description, :presence => true



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :zip_code, :make, :model, 
                  :make2, :model2,
                  :make3, :model3, 
                  :name, :phone, :email,
                  :description


  validates  :zip_code, :presence => true, :format => {:with => /^\d{5}(-?\d{4})?$/}, :on => :create
  validates  :make, :presence => true, :on => :create
  validates  :model, :presence => true, :on => :create

  #the second form is where this values are asked for
  validates :name,  :presence => true, :on => :update
  validates :email, :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}, :on => :update 
  validates :phone, :presence => true, :on => :update
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  before_filter :authenticate

  def index
    @user = User.new
  end
  
  def page2()
  end
  
  def page3()
  end

  def faq
  end

  def contact_us
  end

  def help
  end
  
  def authenticate
    puts AUTHENTICATE 
    if AUTHENTICATE == "yes"
      authenticate_or_request_with_http_basic do |username, password|
        username == USERNAME && password == PASSWORD
      end
    end
  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authorize, :only => [:show, :index]
  
  def new
    @user = User.new
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      #goto form 2
      render 'pages/page2'
    else
      render 'pages/index'
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to page3_path, :notice => "You are done !"
    else
      render 'pages/page2'
    end

  end

  #Require auth to see
  def show
    @user = User.find(params[:id])
  end

  def index 
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    if @user
      @user.destroy
    end
    redirect_to users_url
  end

  private

  def authorize()
    authenticate_or_request_with_http_basic do |username, password|
      username == ADMINUSER && password == ADMINPASSWORD
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container_footer
    %nav.utility
      %ul
        %li= link_to "Home", index_path
        %li= link_to "Contact us", contact_us_path
        %li= link_to "FAQ", faq_path
        %li= link_to "help", help_path

    -#=link_to logo, home_path, :class => "footer_logo"

    .copyright
      %p
        The names and logos for localcar.co are registered trademarks of localcar.co, LLC.
        %br/
        The names and logos for localcar.co are trademarks of localcar.co, LLC.
        %br/
        All text and design is copyright ©2010-2011 localcar.co, LLC. All rights reserved.

app/views/layouts/_googleanalytics.html.haml
:javascript

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-22889888-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/layouts/_header.html.haml
.container_header
  %header.header
    %h1
      =link_to image_tag("Logo.png", :tiltle=> "localcar.co!", :alt => "localcar.co", :width => 198, :height => 80), index_path, :class => "logo"
      %em.tag_line 
        The best price on your new car guaranteed!

       

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
/[if lt IE 8] <haml:loud> stylesheet_link_tag 'ie' </haml:loud>
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title New cars with the best price guaranteed at localcar.co
    %meta{:content => "Get a great deal on your car easily by joining others and making dealerships compete", :name => "description"}
    %meta{:content => "group, car deal, group car", :name => "keywords"}  
    = javascript_include_tag :defaults
    = render 'layouts/stylesheets'    
    = csrf_meta_tag
  %body
    - flash.each do |key, value|
      %div{:class => "flash #{key}"}= value
    %section.container
      = render 'layouts/header'
      %section.content
        = yield
    = render 'layouts/footer'
    = render "layouts/googleanalytics"
    .debug
      = debug(params) if Rails.env.development?

app/views/pages/contact_us.html.haml
%h1 Contact us
%p 
  You can reach us anytime at:
  %strong contact@getautodeal.com

app/views/pages/faq.html.haml
%h1 FAQ
%dl.faq_list
  %dt
    How much does it cost?
    %dd
      The service has no cost. 
  %dt
    Am I going to be spammed with hundreds of quotes from dealers ?
    %dd
      Absolutely not, we won't share any of your data with any dealership. You will only get 1 e-mail from us with all your quotes, then
      you contact any dealer you choose on your terms.
  %dt
    What do I do with the quotes ?
    %dd
      Once you get the quotes you can see which dealers you'd like to contact, the price quoted will be the lowest price so you know exactly
      what you are paying and you can be confident this price is the lowest.

app/views/pages/help.html.haml
%h1 Help
%p 
  E-mail us, and a HUMAN will get back to you on the SAME DAY:
  %strong help@getautodeal.com

app/views/pages/index.html.haml
.statement
  %h1 Join others, make dealerships compete & get the best deal on your new car.
.explanation
  .column
    %h3 1
    %h4 Join others
    %p We group similar local buyers together to increase the incentive for dealerships to present better offers. The more buyers in your area that are trying to buy the same car, the better the deal dealerships are willing to present to you.
  .column
    %h3 2
    %h4 Make dealerships compete
    %p Dealers can see what other dealers are quoting and they can change their quote to beat them so that you get the best price.

  .column
    %h3 3
    %h4 Get the best deal
    %p By combining these 2 strategies, we place power back on your hands, the consumer, increasing transparency and efficiency in the car industry.
   
.registration
  .ceo_message
    %p  Message from our CEO     
    %h3 We will never, for any reason share your contact information with anyone
  .quotes
    %h3 ”Going to every dealer and bargaining for the best price was consuming all my weekends, with localcar.co they did all the work, and I got a great deal” 
    %p - Nadia Laurinci, founder of Elevation labs
    %h3 ”I love driving, but hate buying cars, localcar.co makes it dead easy to buy a new car”
    %p - Alex Torrenegra, founder of Voice123.com, the leading voice over talent site on the web.
  .form_billboard
    %h3 Make Dealerships compete NOW! 
    = render 'users/form'

app/views/pages/page2.html.haml
.statement
  %h1 Almost Done !
.form2_billboard
  = render 'users/form2'
.push

app/views/pages/page3.html.haml
.statement
  %h1 You are done !

#thank_you_note
  %p Thank you for the information, we will match other buyers in your area and will send you quotes from local dealers in the next few days.

.share
  %h2 Share Us
  %p The more people buying cars in your area the better price you get!
  =link_to image_tag("Facebook.png", :alt => "share on facebook"),
                     "http://www.facebook.com/share.php?u=http://localcar.co",
                      :target => "_blank"
  =link_to image_tag("Twitter.png", :alt => "share on facebook"), 
                     "https://twitter.com/intent/tweet?text=Let's buy a car together using www.localcar.co the more people the better price we get !",
                     :target => "_blank"     

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  
  .field
    = f.label :make
    = f.text_field :make
  
  .field
    = f.label :model
    = f.text_field :model  
  
  .actions
    = submit_tag ('Get the best deal!'), :class => "button orange"
  

app/views/users/_form2.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg 
  %p
    %strong If you have more than 1 option please tell us

    .field
      = f.label "Make 2nd choice"
      %br/
      = f.text_field :make2
    
    .field
      = f.label :model
      %br/
      = f.text_field :model2

      
    .field
      = f.label "Make 3rd choice"
      %br/
      = f.text_field :make3
    
    .field
      = f.label :model
      %br/
      = f.text_field :model3  
  
  %p 
    %strong Packages, Options and Accesories
    .field
      = f.label :description
      %br/
      = f.text_area :description 


  %p
    %strong Your Information (Kept private)
  .field
    = f.label :name
    = f.text_field :name
  
  .field
    = f.label :email
    = f.text_field :email
  
  .field
    = f.label :phone
    = f.text_field :phone  
  
  .actions
    = submit_tag ('Finish'), :class => "button orange"
  

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th Name
    %th email
    %th Make
    %th Model
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.make
      %td= user.model
      %td= link_to 'Show', user
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

app/views/users/show.html.haml
%p
  %b User:
  = @user.name
%p
  %b zip code:
  = @user.zip_code
%p
  %b phone
  = @user.phone
%p
  %b Email:
  = @user.email
%p
  %b Make:
  = @user.make
%p
  %b Model:
  = @user.model
%p
  %b Make 2:
  = @user.make2
%p
  %b Model 2: 
  = @user.model2
%p
  %b Make 3:
  = @user.make3
%p
  %b Model 3:
  = @user.model3
%p
  %b Description
  = @user.description